// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QM6YchyxyT5jLuHGbaeVapkBzfb1E6g',
    appId: '1:890250243615:web:f3b6906cc6cbb6b4b3ef2a',
    messagingSenderId: '890250243615',
    projectId: 'venting-e1510',
    authDomain: 'venting-e1510.firebaseapp.com',
    storageBucket: 'venting-e1510.firebasestorage.app',
    measurementId: 'G-KTCZH91ZHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYOrUkN5v9ZSmMizufPYH6NkugZJOMKUg',
    appId: '1:890250243615:android:a8b4cdd9a0983c4fb3ef2a',
    messagingSenderId: '890250243615',
    projectId: 'venting-e1510',
    storageBucket: 'venting-e1510.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKiJPBhvkIyXql5LDwjCCD8fZ83G8Qhl8',
    appId: '1:890250243615:ios:1540e0804b3861aeb3ef2a',
    messagingSenderId: '890250243615',
    projectId: 'venting-e1510',
    storageBucket: 'venting-e1510.firebasestorage.app',
    iosBundleId: 'com.vent.ventingMobileApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKiJPBhvkIyXql5LDwjCCD8fZ83G8Qhl8',
    appId: '1:890250243615:ios:1540e0804b3861aeb3ef2a',
    messagingSenderId: '890250243615',
    projectId: 'venting-e1510',
    storageBucket: 'venting-e1510.firebasestorage.app',
    iosBundleId: 'com.vent.ventingMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3QM6YchyxyT5jLuHGbaeVapkBzfb1E6g',
    appId: '1:890250243615:web:009de50f51941cb2b3ef2a',
    messagingSenderId: '890250243615',
    projectId: 'venting-e1510',
    authDomain: 'venting-e1510.firebaseapp.com',
    storageBucket: 'venting-e1510.firebasestorage.app',
    measurementId: 'G-SEL6TCX8TG',
  );
}
