# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:android)

platform :android do
  desc "Set Gradle Version and Build Number"
  lane :set_full_version do
    version = flutter_version()

    android_set_version_name(version_name: version["version_name"])
    android_set_version_code(version_code: version["version_code"])
  end

  desc "Deploy a new version to the Google Play (alpha / closed testing, draft)"
  lane :deploy do
    version = flutter_version()
    flavor = ENV["FLAVOR"] || "prod"
    package_name = ENV["PACKAGE_NAME"] || "com.vent.ventingMobileApp"
    aab_path = ENV["AAB_PATH"] || "../build/app/outputs/bundle/prodRelease/app-prod-release.aab"

    # Makefile passes repo-root relative paths; Fastlane runs from android/fastlane.
    aab_path = File.expand_path(aab_path, File.join(__dir__, "../.."))

    UI.message("Uploading Venting #{flavor} #{version['version_name']} (#{version['version_code']})")
    UI.message("Package: #{package_name}")
    UI.message("AAB: #{aab_path}")

    UI.user_error!("Missing AAB at #{aab_path}") unless File.exist?(aab_path)

    upload_to_play_store(
      package_name: package_name,
      aab: aab_path,
      track: "alpha", # production | beta | alpha (closed) | internal
      release_status: "draft",
      skip_upload_metadata: false
    )
  end
end
