name: Run Unit Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Flutter Env
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: .fvmrc
        channel: stable
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test
